"""add_professeurs_and_cvs_tables

Revision ID: 07b08e643b0c
Revises: d8fe72943492
Create Date: 2026-05-19 12:19:47.592280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '07b08e643b0c'
down_revision: Union[str, None] = 'd8fe72943492'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professeurs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('mis_a_jour_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('cvs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('professeur_id', sa.BigInteger(), nullable=False),
    sa.Column('nom_original', sa.String(length=255), nullable=False),
    sa.Column('chemin_fichier', sa.String(length=512), nullable=False),
    sa.Column('taille_octets', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('statut', sa.Enum('en_attente', 'en_cours', 'traite', 'erreur', name='cvstatut'), nullable=False),
    sa.Column('texte_brut', sa.Text(), nullable=True),
    sa.Column('message_erreur', sa.Text(), nullable=True),
    sa.Column('televerse_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('traite_le', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['professeur_id'], ['professeurs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('professeur_id')
    )
    op.create_index(op.f('ix_cvs_statut'), 'cvs', ['statut'], unique=False)
    # ### end Alembic commands ###

    # Backfill: create one professeur row per existing user with role='PROF'.
    op.execute(
        "INSERT INTO professeurs (user_id) "
        "SELECT id FROM users WHERE role = 'PROF'"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cvs_statut'), table_name='cvs')
    op.drop_table('cvs')
    op.drop_table('professeurs')
    # ### end Alembic commands ###
    sa.Enum(name='cvstatut').drop(op.get_bind(), checkfirst=False)
