"""create_langues_table

Revision ID: 359cdb7e1253
Revises: b003032d001e
Create Date: 2026-05-20 16:33:43.458631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '359cdb7e1253'
down_revision: Union[str, None] = 'b003032d001e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('langues',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('professeur_id', sa.BigInteger(), nullable=False),
    sa.Column('langue', sa.String(length=60), nullable=False),
    sa.Column('niveau', sa.Enum('A1', 'A2', 'B1', 'B2', 'C1', 'C2', 'natif', name='langue_niveau'), nullable=False),
    sa.Column('source', postgresql.ENUM('llm', 'manual', name='source_origine', create_type=False), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['professeur_id'], ['professeurs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_langues_professeur_id'), 'langues', ['professeur_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index(op.f('ix_langues_professeur_id'), table_name='langues')
    op.drop_table('langues')
    op.execute('DROP TYPE IF EXISTS langue_niveau')
