"""add_affectation_tables

Revision ID: 675089b221d1
Revises: 849d836e4480
Create Date: 2026-05-22 01:51:01.359390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '675089b221d1'
down_revision: Union[str, None] = '849d836e4480'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cours',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('credits', sa.SmallInteger(), nullable=True),
    sa.Column('heures', sa.SmallInteger(), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('mis_a_jour_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('programmes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('departement', sa.String(length=120), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('mis_a_jour_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('sessions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('annee', sa.SmallInteger(), nullable=False),
    sa.Column('semestre', sa.Enum('printemps', 'ete', 'automne', 'hiver', name='semestre'), nullable=False),
    sa.Column('statut', sa.Enum('planifiee', 'ouverte', 'fermee', name='session_statut'), server_default='planifiee', nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('mis_a_jour_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('annee', 'semestre', name='uq_session_annee_semestre')
    )
    op.create_table('cours_competences',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('cours_id', sa.BigInteger(), nullable=False),
    sa.Column('nom', sa.String(length=120), nullable=False),
    sa.Column('importance', sa.SmallInteger(), server_default='3', nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('importance BETWEEN 1 AND 5', name='ck_cours_competences_importance_1_5'),
    sa.ForeignKeyConstraint(['cours_id'], ['cours.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cours_competences_cours_id'), 'cours_competences', ['cours_id'], unique=False)
    op.create_table('etapes_programme',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('programme_id', sa.BigInteger(), nullable=False),
    sa.Column('ordre', sa.SmallInteger(), nullable=False),
    sa.Column('nom', sa.String(length=120), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('programme_id', 'ordre', name='uq_etape_programme_ordre')
    )
    op.create_index(op.f('ix_etapes_programme_programme_id'), 'etapes_programme', ['programme_id'], unique=False)
    op.create_table('ponderations_sessions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('w1', sa.Numeric(precision=4, scale=3), server_default='0.400', nullable=False),
    sa.Column('w2', sa.Numeric(precision=4, scale=3), server_default='0.300', nullable=False),
    sa.Column('w3', sa.Numeric(precision=4, scale=3), server_default='0.200', nullable=False),
    sa.Column('w4', sa.Numeric(precision=4, scale=3), server_default='0.100', nullable=False),
    sa.Column('xai_actif', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('mis_a_jour_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ABS((w1 + w2 + w3 + w4) - 1.0) <= 0.001', name='ck_ponderations_somme_1'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('affectations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('professeur_id', sa.BigInteger(), nullable=False),
    sa.Column('cours_id', sa.BigInteger(), nullable=False),
    sa.Column('score_total', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('score_comp', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('score_exp', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('score_hist', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('score_sem', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('statut', sa.Enum('proposee', 'validee', 'rejetee', name='affectation_statut'), server_default='proposee', nullable=False),
    sa.Column('valide_par_user_id', sa.BigInteger(), nullable=True),
    sa.Column('valide_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('mis_a_jour_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cours_id'], ['cours.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['professeur_id'], ['professeurs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['valide_par_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'professeur_id', 'cours_id', name='uq_affectation_session_prof_cours')
    )
    op.create_index(op.f('ix_affectations_cours_id'), 'affectations', ['cours_id'], unique=False)
    op.create_index(op.f('ix_affectations_professeur_id'), 'affectations', ['professeur_id'], unique=False)
    op.create_index(op.f('ix_affectations_session_id'), 'affectations', ['session_id'], unique=False)
    op.create_table('cours_etape_programme',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('programme_id', sa.BigInteger(), nullable=False),
    sa.Column('etape_id', sa.BigInteger(), nullable=False),
    sa.Column('cours_id', sa.BigInteger(), nullable=False),
    sa.Column('categorie', sa.Enum('obligatoire', 'choix_francais', 'choix_anglais', name='categorie_cours'), server_default='obligatoire', nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cours_id'], ['cours.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['etape_id'], ['etapes_programme.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('programme_id', 'etape_id', 'cours_id', name='uq_cursus_programme_etape_cours')
    )
    op.create_index(op.f('ix_cours_etape_programme_cours_id'), 'cours_etape_programme', ['cours_id'], unique=False)
    op.create_index(op.f('ix_cours_etape_programme_etape_id'), 'cours_etape_programme', ['etape_id'], unique=False)
    op.create_index(op.f('ix_cours_etape_programme_programme_id'), 'cours_etape_programme', ['programme_id'], unique=False)
    op.create_table('affectation_feedback',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('affectation_id', sa.BigInteger(), nullable=False),
    sa.Column('note', sa.SmallInteger(), nullable=False),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('valide_par_user_id', sa.BigInteger(), nullable=True),
    sa.Column('date_eval', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('note BETWEEN 1 AND 5', name='ck_feedback_note_1_5'),
    sa.ForeignKeyConstraint(['affectation_id'], ['affectations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['valide_par_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_affectation_feedback_affectation_id'), 'affectation_feedback', ['affectation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_affectation_feedback_affectation_id'), table_name='affectation_feedback')
    op.drop_table('affectation_feedback')
    op.drop_index(op.f('ix_cours_etape_programme_programme_id'), table_name='cours_etape_programme')
    op.drop_index(op.f('ix_cours_etape_programme_etape_id'), table_name='cours_etape_programme')
    op.drop_index(op.f('ix_cours_etape_programme_cours_id'), table_name='cours_etape_programme')
    op.drop_table('cours_etape_programme')
    op.drop_index(op.f('ix_affectations_session_id'), table_name='affectations')
    op.drop_index(op.f('ix_affectations_professeur_id'), table_name='affectations')
    op.drop_index(op.f('ix_affectations_cours_id'), table_name='affectations')
    op.drop_table('affectations')
    op.drop_table('ponderations_sessions')
    op.drop_index(op.f('ix_etapes_programme_programme_id'), table_name='etapes_programme')
    op.drop_table('etapes_programme')
    op.drop_index(op.f('ix_cours_competences_cours_id'), table_name='cours_competences')
    op.drop_table('cours_competences')
    op.drop_table('sessions')
    op.drop_table('programmes')
    op.drop_table('cours')
    # Drop ENUM types — créés par cette migration, doivent être supprimés ici.
    op.execute('DROP TYPE IF EXISTS categorie_cours')
    op.execute('DROP TYPE IF EXISTS affectation_statut')
    op.execute('DROP TYPE IF EXISTS session_statut')
    op.execute('DROP TYPE IF EXISTS semestre')
    # ### end Alembic commands ###
