"""create_experiences_table

Revision ID: 79fc2de90823
Revises: f6af933b2298
Create Date: 2026-05-20 16:29:50.716502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '79fc2de90823'
down_revision: Union[str, None] = 'f6af933b2298'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiences',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('professeur_id', sa.BigInteger(), nullable=False),
    sa.Column('poste', sa.String(length=255), nullable=False),
    sa.Column('employeur', sa.String(length=255), nullable=False),
    sa.Column('annee_debut', sa.Integer(), nullable=False),
    sa.Column('annee_fin', sa.Integer(), nullable=True),
    sa.Column('description_courte', sa.Text(), nullable=True),
    sa.Column('source', postgresql.ENUM('llm', 'manual', name='source_origine', create_type=False), nullable=False),
    sa.Column('ordre', sa.Integer(), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['professeur_id'], ['professeurs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiences_professeur_id'), 'experiences', ['professeur_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_experiences_professeur_id'), table_name='experiences')
    op.drop_table('experiences')
    # ### end Alembic commands ###
