"""add_resume_profil_to_professeurs

Revision ID: 849d836e4480
Revises: 359cdb7e1253
Create Date: 2026-05-20 16:34:47.403423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '849d836e4480'
down_revision: Union[str, None] = '359cdb7e1253'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('professeurs', sa.Column('resume_profil', sa.Text(), nullable=True))
    op.add_column('professeurs', sa.Column('resume_profil_source', postgresql.ENUM('llm', 'manual', name='source_origine', create_type=False), server_default='llm', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('professeurs', 'resume_profil_source')
    op.drop_column('professeurs', 'resume_profil')
    # ### end Alembic commands ###
