"""make_password_hash_nullable_and_add_setup_tokens

Revision ID: a0f6c61f68c2
Revises: b750dd8e938f
Create Date: 2026-05-23 23:50:32.419248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a0f6c61f68c2'
down_revision: Union[str, None] = 'b750dd8e938f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_setup_tokens',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_setup_tokens_token'), 'password_setup_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_password_setup_tokens_user_id'), 'password_setup_tokens', ['user_id'], unique=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
    op.drop_index(op.f('ix_password_setup_tokens_user_id'), table_name='password_setup_tokens')
    op.drop_index(op.f('ix_password_setup_tokens_token'), table_name='password_setup_tokens')
    op.drop_table('password_setup_tokens')
    # ### end Alembic commands ###
