"""create_formations_table

Revision ID: b003032d001e
Revises: 79fc2de90823
Create Date: 2026-05-20 16:32:44.069694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = 'b003032d001e'
down_revision: Union[str, None] = '79fc2de90823'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('formations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('professeur_id', sa.BigInteger(), nullable=False),
    sa.Column('diplome', sa.String(length=255), nullable=False),
    sa.Column('etablissement', sa.String(length=255), nullable=False),
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.Column('source', postgresql.ENUM('llm', 'manual', name='source_origine', create_type=False), nullable=False),
    sa.Column('ordre', sa.Integer(), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['professeur_id'], ['professeurs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_formations_professeur_id'), 'formations', ['professeur_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_formations_professeur_id'), table_name='formations')
    op.drop_table('formations')
    # ### end Alembic commands ###
