"""add_embedding_columns

Revision ID: b60c46ed110a
Revises: 675089b221d1
Create Date: 2026-05-22 02:00:28.938679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'b60c46ed110a'
down_revision: Union[str, None] = '675089b221d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cours', sa.Column('embedding', postgresql.ARRAY(sa.Float()), nullable=True))
    op.add_column('professeurs', sa.Column('embedding', postgresql.ARRAY(sa.Float()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('professeurs', 'embedding')
    op.drop_column('cours', 'embedding')
    # ### end Alembic commands ###
