"""add_actif_to_users

Revision ID: b750dd8e938f
Revises: b60c46ed110a
Create Date: 2026-05-23 00:35:47.808368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b750dd8e938f'
down_revision: Union[str, None] = 'b60c46ed110a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('actif', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'actif')
    # ### end Alembic commands ###
