"""create_competences_table

Revision ID: f6af933b2298
Revises: 07b08e643b0c
Create Date: 2026-05-20 16:23:47.583564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f6af933b2298'
down_revision: Union[str, None] = '07b08e643b0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competences',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('professeur_id', sa.BigInteger(), nullable=False),
    sa.Column('nom', sa.String(length=120), nullable=False),
    sa.Column('niveau', sa.Enum('debutant', 'intermediaire', 'avance', 'expert', name='competence_niveau'), nullable=False),
    sa.Column('source', sa.Enum('llm', 'manual', name='source_origine'), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['professeur_id'], ['professeurs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competences_professeur_id'), 'competences', ['professeur_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index(op.f('ix_competences_professeur_id'), table_name='competences')
    op.drop_table('competences')
    # Drop ENUM types — créés par la migration, doivent être supprimés ici.
    # source_origine est partagé : sera recréé par les migrations suivantes
    # (experiences, formations, langues) avec create_type=False.
    op.execute('DROP TYPE IF EXISTS competence_niveau')
    op.execute('DROP TYPE IF EXISTS source_origine')
